services:
  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    environment:
      - DB__HOST=mongo
    profiles: [services]

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB__USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB__PASSWORD
      - MONGO_INITDB_DATABASE=$DB__DATABASE_NAME
      - DB_PASSWORD=$DB__PASSWORD
      - DB_USERNAME=$DB__USERNAME
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - mongo_storage:/data/db
    profiles: [infra]

volumes:
  mongo_storage:
  pycommon:
